import Head from "next/head";
import { motion } from "framer-motion";
import { fadeIn } from "../variants";
import { TypeAnimation } from "react-type-animation";
import { ImTelegram } from "react-icons/im";
import { FaPhone } from "react-icons/fa6";

import { FiInstagram } from "react-icons/fi";


export default function Home():any {
  return (
    <>
      <Head>
        <title>Million Motors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className="smth  ">
        <div className="flex justify-center h-[50px] ">
          <img className="w-[140px] h-[65px] " src="/logo.png" alt="image" />
        </div>

        <div className="text-center for-text ">
          <TypeAnimation
            sequence={[
              "ПРОДАЖА АВТОМОБИЛЕЙ И ЭЛЕКТРОМОБИЛЕЙ",
              2000,
              "АВТОМОБИЛИ В НАЛИЧИЕ И ПОД ЗАКАЗ",
              2000,
              "БОЛЬШОЙ АССОРТИМЕНТ АВТОМОБИЛЕЙ ",
              2000,
              "ОПЛАТА НАЛИЧНЫМИ И ПЕРЕЧИЛЕНИЯМИ ",
              2000,
              "АВТОКРЕДИТ НА ВАШЕ ИМЯ ЧЕРЕЗ БАНК  ",
              2000,
              "ПРИЕМЛЕМЫЕ ЦЕНЫ ",
              2000,
            ]}
            speed={50}
            className="text-accent"
            wrapper="span"
            repeat={Infinity}
          />

          
            <motion.div
              variants={fadeIn("right", 0.5)}
              initial="hidden"
              whileInView={"show"}
              viewport={{ once: false, amount: 0.5 }}
              className="w-full mt-[30px] flex justify-center items-center h-[50px] "
            >
              <FiInstagram className="insta" style={{ color: "red" }} />

              <a href="https://www.instagram.com/millionmotors.uz?igsh=eWtmaHhyeTVkMzhx&utm_source=qr">
                <p className="text-[white] pl-[8px] font-bold ">Instagram</p>
              </a>
            </motion.div>
        

          
            <motion.div
              variants={fadeIn("left", 0.6)}
              initial="hidden"
              whileInView={"show"}
              viewport={{ once: false, amount: 0.6 }}
              className="w-full mt-[30px] flex justify-center items-center h-[20px] "
            >
              <ImTelegram className="telega" style={{ color: "blue" }} />

              <a href="https://t.me/millionmotors_uz">
                <p className="pl-[8px] text-[white] font-bold ">Telegram</p>
              </a>

            </motion.div>
        
        </div>
        <div className="w-full pl-[10px]  ">
          <div className="flex items-center justify-between">
            <FaPhone style={{ color: "green" }} />
            <p className="text-white pr-[7px] text-[20px] font-bold ">
              <a href="tel:+99880265555">+998 88 026-55-55</a>
            </p>
          </div>
          <div className="flex items-center justify-between">
            <FaPhone style={{ color: "green" }} />
            <p className="text-white pr-[7px] text-[20px] font-bold ">
              <a href="tel:+998880285555">+998 88 028-55-55 </a>
            </p>
          </div>
          <div className="flex items-center justify-between">
            <FaPhone style={{ color: "green" }} />
            <p className="text-white pr-[7px] text-[20px] font-bold ">
              <a href="tel:+99880295555">+998 88 029-55-55 </a>
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
